services:
  # surrealdb:
  #   image: surrealdb/surrealdb:latest
  #   entrypoint:
  #     - /surreal
  #     - start
  #     - --user
  #     - root
  #     - --pass
  #     - root
  #     - file:/db/data.db
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - ./.db:/db
  redis:
    container_name: redis_service
    image: redis:7.0-alpine
    ports:
      - 6379:6379
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - common

networks:
  common:
    name: common
    driver: bridge
